services:
  client:
    build:
      context: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - custom_network
    restart: always
    # command: npm run serve -- --port 3000 --host 0.0.0.0
    command: npm run serve-docker
  server:
    build:
      context: ../server
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ../server:/app
    networks:
      - custom_network
    restart: always
    command: json-server --watch db.json --port 5000 --host 0.0.0.0
networks:
  custom_network:
    driver: bridge 